services:

  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              count: all

  chat_app:
    build: ./chat_app
    container_name: chat_app
    network_mode: host
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
